### ISSUE TITLE
Deposit gak kebaca ya bro?

### ISSUE THREAD

**Issue by 0xAndrs** [Zlkcyber/hanafuda#1]

**Comment by Zlkcyber** [comment]
ke baca asal deposit pertama kali diwebnya and wallet gak ada ens

**Comment by 0xAndrs** [comment]
sudah depo manual pertamanya. 
Ens apa ya?

**Comment by Zlkcyber** [comment]
Domain name, seperti nama.eth, nama.base.eth dll

**Comment by 0xAndrs** [comment]
Ohh pantesan sy pake domain. Makasih bro

**Comment by CDZ0D** [comment]
deposit gk kebaca min
